### PR TITLE
#26 Cross and Ticks fonts in arrow component

### PR DESCRIPTION
**Pull request by lindsaymacvean**

### CODE REVIEW

**Comment by lindsaymacvean** [comment]
image
It seems on question 6 of this brick the crosses and ticks are not formatting correctly.
https://learning-fortress-front-pr-189.herokuapp.com/play/brick/art_history/review

**Comment by aromakh** [comment]
#26

**Comment by lindsaymacvean** [comment]
This has been resolved for Sort and Arrow. Can we also resolve for SingleChoice MultipleChoice and ShortAnswer

**Comment by aromakh** [comment]
Fixed checkbox align in one row.
image

image

**Comment by aromakh** [comment]
SortAnswerComponent

**Comment by lindsaymacvean** [comment]
@aromakh I added the ticks and questions to the remaining questions. You can have a look at what I did. 

I made the PR messy because I was running a script to backup and restore the content to the dev database in the background as I made changes to the production database, apologies for this.

**Pull request merged**
